version: '3.8'
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.12.5
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_SERVICES=iam,lambda,dynamodb,sqs
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_DOCKER_NETWORK=podcast-radio-podcast-service_default
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
