name: Deploy Release

on:
  create:
    branches:
      - 'RELEASE-**'

jobs:
  deploy_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Install lerna
        run: npm install -g lerna
      - name: Bootstrap
        run: lerna bootstrap
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Setup npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" > .npmrc
      - name: Deploy
        run: yarn run deploy