name: Deploy Infrastructure to DEV

on: workflow_dispatch

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Setup npmrc auth
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Setup npmrc
        run: printf "//npm.pkg.github.com/:_authToken=${{secrets.NPM_AUTH_TOKEN}}\n@drspacemanphd:registry=https://npm.pkg.github.com" > .npmrc
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_INFRA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_INFRA_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup terraform cli
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.5
      - name: Install lerna
        run: npm install -g lerna
      - name: Build lambdas
        run: lerna run build:deployment
      - name: Initialize DEV workspace
        run: cd ./infrastructure/dev && terraform init
      - name: Apply terraform
        run: cd ./infrastructure/dev && terraform apply --auto-approve
