name: Deploy Infrastructure to DEV

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_INFRA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_INFRA_AWS_SECRET_ACCESS_KEY }}
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.5
      - name: Initialize DEV workspace
        run: cd ./infrastructure/dev && terraform init
      - name: terraform plan
        run: cd ./infrastructure/dev && terraform plan
