name: Deploy Infrastructure to DEV

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.5
      - name: Use DEV as local workspace
        run: cd ./infrastructure/dev
      - name: Check dir
        run: ls -al
      - name: Initialize DEV workspace
        run: terraform init
      - name: terraform plan
        run: terraform plan
