name: Integration Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Create npmrc
        uses: ferluisxd/create-npmrc@3
        with:
          org_name: podcast-radio-web
        env:
          AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Install lerna
        run: npm install -g lerna
      - name: Bootstrap
        run: lerna bootstrap
      - name: Run Integration Tests
        run: bash ./scripts/integration-tests.sh