name: Integration Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Setup npmrc
        run: printf "//npm.pkg.github.com/:_authToken=${{secrets.NPM_AUTH_TOKEN}}\n@drspacemanphd:registry=https://npm.pkg.github.com" > .npmrc
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Install lerna
        run: npm install -g lerna
      - name: Build
        run: lerna run build
      - name: Run Integration Tests
        run: bash ./scripts/integration-tests.sh